# Generated by Django 3.0.2 on 2020-01-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('bg', 'Български'), ('en', 'English'), ('fr', 'Français')], max_length=2),
        ),
    ]
