# Generated by Django 3.0.2 on 2020-01-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumdetails',
            name='language',
            field=models.CharField(choices=[('bg', 'Български'), ('en', 'English'), ('fr', 'Français')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='albumdetails',
            unique_together={('album', 'language')},
        ),
    ]
