# Generated by Django 3.0.2 on 2020-01-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200119_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(verbose_name='is hidden')),
                ('length', models.TimeField()),
                ('release_date', models.DateField(verbose_name='release date')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('original_title', models.CharField(max_length=255, verbose_name='original title')),
                ('youtube', models.URLField(verbose_name='youtube link')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='SongLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.TextField()),
                ('english_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='english title')),
                ('english_lyrics', models.TextField(blank=True, null=True, verbose_name='english lyrics')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
        ),
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, verbose_name='file path')),
                ('file_type', models.CharField(choices=[('aac', 'Advanced Audio Codec'), ('ogg', 'Ogg Vorbis'), ('opus', 'Opus')], max_length=35, verbose_name='file type')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
            options={
                'unique_together': {('song', 'file_type')},
            },
        ),
        migrations.CreateModel(
            name='SongDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('bg', 'Български'), ('en', 'English'), ('fr', 'Français')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
            options={
                'unique_together': {('song', 'language')},
            },
        ),
    ]
