# Generated by Django 3.0.2 on 2020-01-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_songdescription_songfile_songlyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='youtube link'),
        ),
    ]
