# Generated by Django 3.0.2 on 2020-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200119_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdescription',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songdescription',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
