# Generated by Django 3.0.2 on 2020-01-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_songlyrics_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumdetails',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_details', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='songdescription',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_descriptions', to='music.Song'),
        ),
        migrations.AlterField(
            model_name='songfile',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_files', to='music.Song'),
        ),
        migrations.AlterField(
            model_name='songlyrics',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song_lyrics', to='music.Song'),
        ),
    ]
