# Generated by Django 3.0.2 on 2020-01-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200121_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='album order'),
        ),
    ]
