# Generated by Django 3.0.2 on 2020-01-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20200125_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_order',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='album order'),
        ),
    ]
